recetas:
    path: /recetas
    controller: App\Controller\RecetaController::index

register:
    path: /registrar
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout